service: floorcap-bot
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  serverless-offline:
    noPrependStageInUrl: true

package:
  exclude:
    - node_modules/serverless*/**

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: dev
  region: us-east-1
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024
  environment:
    STAGE: ${self:custom.stage}
    APP_KEY: ${env:APP_KEY}
    APP_SECRET: ${env:APP_SECRET}
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}
    ACCESS_SECRET: ${env:ACCESS_SECRET}

functions:
  tweetPrices:
    handler: app/handler.gm
    events:
      - http:
          path: gm
          method: get
      - schedule:
          name: ${self:service}-${self:custom.stage}-tweet-gm
          description: "Tweet GM"
          rate: cron(0 13 ? * MON-FRI *)
          enabled: true
